version: "3.9"

services:
  valkey:
    image: valkey/valkey-bundle:9-alpine
    container_name: valkey
    ports:
      - "6379:6379"
    restart: unless-stopped

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    depends_on:
      - valkey
    restart: unless-stopped
