// Brand → logo URL. Wikimedia Commons is hotlinkable; SVGs scale crisply.

export const BRAND_LOGOS = {
  Apple:       "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
  Samsung:     "https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg",
  Sony:        "https://upload.wikimedia.org/wikipedia/commons/c/ca/Sony_logo.svg",
  Microsoft:   "https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg",
  Google:      "https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg",
  Amazon:      "https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg",
  Dell:        "https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg",
  DELL:        "https://upload.wikimedia.org/wikipedia/commons/4/48/Dell_Logo.svg",
  HP:          "https://upload.wikimedia.org/wikipedia/commons/a/ad/HP_logo_2008.svg",
  Lenovo:      "https://upload.wikimedia.org/wikipedia/commons/b/be/Lenovo_%282015%29.svg",
  LG:          "https://upload.wikimedia.org/wikipedia/commons/8/8d/LG_logo_%282014%29.svg",
  Asus:        "https://upload.wikimedia.org/wikipedia/commons/2/2c/ASUS_Logo.svg",
  Bose:        "https://upload.wikimedia.org/wikipedia/commons/8/86/Bose_logo.svg",
  GoPro:       "https://upload.wikimedia.org/wikipedia/commons/5/5b/GoPro_logo.svg",
  Anker:       "https://upload.wikimedia.org/wikipedia/commons/d/d9/Anker_logo.svg",
  JBL:         "https://upload.wikimedia.org/wikipedia/commons/9/9c/JBL_logo.svg",
  Canon:       "https://upload.wikimedia.org/wikipedia/commons/8/86/Canon_wordmark.svg",
  Fujifilm:    "https://upload.wikimedia.org/wikipedia/commons/8/8c/Fujifilm_logo.svg",
  DJI:         "https://upload.wikimedia.org/wikipedia/commons/b/b5/DJI_logo.svg",
  Philips:     "https://upload.wikimedia.org/wikipedia/commons/5/53/Philips_logo_new.svg",
  Ring:        "https://upload.wikimedia.org/wikipedia/commons/d/d4/Ring_logo.svg",
  "TP-Link":   "https://upload.wikimedia.org/wikipedia/commons/4/4d/TP-Link-Logo.svg",
  TCL:         "https://upload.wikimedia.org/wikipedia/commons/c/c3/TCL_logo.svg",
  Sennheiser:  "https://upload.wikimedia.org/wikipedia/commons/4/4f/Sennheiser-Logo.svg",
  Insta360:    "https://upload.wikimedia.org/wikipedia/commons/3/3f/Insta360_Logo.svg",
  Fitbit:      "https://upload.wikimedia.org/wikipedia/commons/8/82/Fitbit_logo16.svg",
  Nike:        "https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg",
  Adidas:      "https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg",
  Wilson:      "https://upload.wikimedia.org/wikipedia/commons/5/5f/Wilson_Sporting_Goods_logo.svg",
  Spalding:    "https://upload.wikimedia.org/wikipedia/commons/5/52/Spalding_logo.svg",
  Decathlon:   "https://upload.wikimedia.org/wikipedia/commons/3/3a/Decathlon_Logo.svg",
  Nestle:      "https://upload.wikimedia.org/wikipedia/commons/8/88/Nestl%C3%A9.svg",
  Kelloggs:    "https://upload.wikimedia.org/wikipedia/commons/c/c2/Kellogg%27s_logo.svg",
  "Coca-Cola": "https://upload.wikimedia.org/wikipedia/commons/c/ce/Coca-Cola_logo.svg",
  PepsiCo:     "https://upload.wikimedia.org/wikipedia/commons/0/0f/Pepsi_logo_2014.svg",
  Lays:        "https://upload.wikimedia.org/wikipedia/commons/8/8f/Lay%27s_logo_2019.svg",
  Cadbury:     "https://upload.wikimedia.org/wikipedia/commons/e/eb/Cadbury_2020.svg",
  Parker:      "https://upload.wikimedia.org/wikipedia/commons/0/01/Parker_Pen_logo.svg",
  "Faber-Castell": "https://upload.wikimedia.org/wikipedia/commons/4/4d/Faber-Castell_Logo.svg",
  Moleskine:   "https://upload.wikimedia.org/wikipedia/commons/e/eb/Moleskine_logo.svg",
  SanDisk:     "https://upload.wikimedia.org/wikipedia/commons/2/27/SanDisk_logo.svg",
  WD:          "https://upload.wikimedia.org/wikipedia/commons/4/4f/Western_Digital_logo.svg",
};

export function logoFor(brand) {
  return BRAND_LOGOS[brand] || null;
}
