export const keys = {
  user: (id: string) => `shopmind:user:${id}`,
  userEmail: (email: string) => `shopmind:user:email:${email.toLowerCase()}`,
  session: (id: string) => `shopmind:session:${id}`,
  reset: (token: string) => `shopmind:reset:${token}`,
  product: (id: string) => `shopmind:product:${id}`,
  category: (id: string) => `shopmind:category:${id}`,
  inventory: (id: string) => `shopmind:inventory:${id}`,
  cartUser: (id: string) => `shopmind:cart:user:${id}`,
  cartGuest: (id: string) => `shopmind:cart:guest:${id}`,
  wishlist: (id: string) => `shopmind:wishlist:${id}`,
  recent: (id: string) => `shopmind:recent:${id}`,
  order: (id: string) => `shopmind:order:${id}`,
  userOrders: (id: string) => `shopmind:orders:user:${id}`,
  reservation: (id: string) => `shopmind:reservation:${id}`,
  coupon: (code: string) => `shopmind:coupon:${code.toUpperCase()}`,
  couponUsage: (code: string) => `shopmind:coupon:usage:${code.toUpperCase()}`,
  conversation: (id: string) => `shopmind:conversation:${id}`,
  aiCache: (hash: string) => `shopmind:ai:cache:${hash}`,
  trend: (name: "views" | "clicks" | "carts" | "purchases") => `shopmind:trend:${name}`,
  personal: (id: string) => `shopmind:personal:${id}:scores`,
  rate: (scope: string, identity: string) => `shopmind:rate:${scope}:${identity}`,
  geoDrivers: "shopmind:geo:drivers",
  streamOrders: "shopmind:stream:orders",
  streamAnalytics: "shopmind:stream:analytics",
  streamInventory: "shopmind:stream:inventory",
  pubInventory: "shopmind:pub:inventory",
  pubTrending: "shopmind:pub:trending",
  pubOrder: (id: string) => `shopmind:pub:orders:${id}`,
  pubUserNotifications: (id: string) => `shopmind:pub:notifications:${id}`
};
